# Generated by Django 4.1.5 on 2023-02-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
